services:
  client:
    build:
      context: /Client-master
    image: client_image:latest
    ports:
      - 8080:8080
    volumes:
      - ./volume:/app/data

  server:
    build:
      context: /Server-master
    image: server_image:latest
    ports:
      - 8081:8081

  client_admin:
    build:
      context: /ClientAdmin-master
    image: client_admin_image:latest
    ports:
      - 8082:8082
