services:
  client:
    build:
      context: /Client
    image: client_image:latest
    ports:
      - 8080:8080
    volumes:
      - ./volume:/app/data
    develop:
      watch:
        - path: ./Client
          action: rebuild
    environment:
      SPRING_PROFILES_ACTIVE: docker


  server:
    build:
      context: /Server
    image: server_image:latest
    ports:
      - 8081:8081
    develop:
      watch:
        - path: ./Server
          action: rebuild

  client_admin:
    build:
      context: /ClientAdmin
    image: client_admin_image:latest
    ports:
      - 8082:8082
    develop:
      watch:
        - path: ./ClientAdmin
          action: rebuild
